# This pre-commit configuration file configures clang-format to run upon running the command line command 'git commit'.
# The pre-commit git hook is installed using the command line command 'pre-commit install'.

exclude: '^Software/src/lib/'  # don't run hooks on external libraries

# This continuous integration section is optional, and enables autoupdating the pre-commit configuration, ensuring that
# the hook versions are kept up to date.
ci:
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.5
  hooks:
  - id: clang-format
    args: [-Werror]  # change formatting warnings to errors, hook includes -i (Inplace edit) by default
    types_or: [c++, c]  # override default file types to only C and CPP files
